services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '%kernel.project_dir%/src/*'

    App\Controller\:
        resource: '%kernel.project_dir%/src/Controller/'
        tags: ['controller.service_arguments']
