framework:
    secret: '%env(APP_SECRET)%'
    validation:
        enabled: true
        enable_annotations: true
    php_errors:
        log: true
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    serializer:
        enabled: true
        enable_annotations: true
    property_info:
        enabled: true
